// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fphrgrttnwgghdccylrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwaHJncnR0bndnZ2hkY2N5bHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NDczOTAsImV4cCI6MjA1OTAyMzM5MH0.jXS6qHnkEr81ufJPxRsirIHoxT0BylPtROrHs0Uva-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);